### ISSUE TITLE
Please add EncodeHints/EncodeHintType in qrcode.dart

### ISSUE THREAD

**Issue by YojiroMotoba** [xvrh/zxing-dart#10]
<img width="309" alt="スクリーンショット 2022-10-01 23 34 34" src="https://user-images.githubusercontent.com/35243890/193414508-5bef8f82-8cd4-4e95-b714-11d3a4b60154.png">

I can't import EncodeHints

**Comment by YojiroMotoba** [comment]
@xvrh 

Oh sorry something is wrong

https://github.com/xvrh/zxing-dart/actions/runs/3181579826

I will try it

**Comment by YojiroMotoba** [comment]
@xvrh 

I found error.

`Error:  found changed files after build. please run 'dart tool/prepare_submit.dart' and check in all changes`

Can you rerun job?

**Comment by xvrh** [comment]
@YojiroMotoba Thanks, I fixed it directly on master.

**Comment by YojiroMotoba** [comment]
@xvrh Thank you for responding to it promptly! 😄
