### ISSUE TITLE
Cannot detect QR in JPG

### ISSUE THREAD

**Issue by ronpetit** [xvrh/zxing-dart#14]
Hello!

I have been using this package for about two weeks and it was working pretty well, however, suddenly, and I don't know why, the package started to not be able to decode QR in JPG images, even high quality images taken with my phone.

I don't know if this is exactly over JPGs, but I have a PNG file of a programmatically generated QR which have no problems to be decoded, but if I print that QR and take a picture with my phone camera 90% of the time the package won't decode it

I don't know what changed, because a couple days before it was working well, I'm starting to think about the light on the room, but the QR images I'm sending to the package are pretty clear

Here is my code

```dart
void main(List<String> arguments) {
  var image = decodeImage(File('/Users/rpetit/Downloads/IMG_0292.JPG').readAsBytesSync())!;

  LuminanceSource source = RGBLuminanceSource(image.width, image.height,
      image.getBytes(format: Format.abgr).buffer.asInt32List());
  var bitmap = BinaryBitmap(HybridBinarizer(source));

  var reader = QRCodeReader();
  final hints = DecodeHints();
  hints.put(DecodeHintType.tryHarder);
  var result = reader.decode(bitmap, hints: hints);
  print(result.text);
}
```
I'm receiving a NotFoundException when trying to decode the bitmap

And this is an example of the QR I'm trying to scan

![IMG_0292](https://user-images.githubusercontent.com/5855265/206177910-e6b06fc7-dabc-4c79-a689-119be5927d56.JPG)

**Comment by ronpetit** [comment]
@xvrh Can you try to replicate my problem with the image I left?, any kind of hint would be really appreciated, I'm sure I must be doing something wrong which I cannot detect

**Comment by GoRadioGo** [comment]
" ... I'm receiving a NotFoundException when trying to decode the bitmap ..."
Hmmm ... what do you mean by "decode the bitmap" ? On exactly which line of code is the exception occurring ?
Bring out the debugger, and you will know quickly.

File('/Users/rpetit/Downalods/IMG_0292') ...  should that filename have a '.jpg' or '.png' extension ?

**Comment by GoRadioGo** [comment]
What if you use the simpler QR decoding example on this Github "code" page ?

**Comment by ronpetit** [comment]
> What if you use the simpler QR decoding example on this Github "code" page ?

If you check my code I’m actually just copy and pasting that example, just changing the image file and adding a hint

Even though, I have tried with the exact example and my file and still it doesn’t work

It does work if I actually use the same file as the example, but in my application I need the package to recognize pictures taken from a camera, so digital QR codes do not work for what I need

**Comment by ronpetit** [comment]
Any ideas? @xvrh still have the issue, have tried with QRs generated by the library itself, and still it doesn't work

Sorry to bother you

**Comment by xvrh** [comment]
@ronpetit I quickly tried and get the same surprising result as you.

I also tried with the original zxing java library and it fails too. But with the zxing Android test app, it works! So there is something weird here.

I'm still looking at it...

**Comment by ronpetit** [comment]
> @ronpetit I quickly tried and get the same surprising result as you.
> 
> I also tried with the original zxing java library and it fails too. But with the zxing Android test app, it works! So there is something weird here.
> 
> I'm still looking at it...

Thanks a lot for your answer! if there is anything I can do to help you just let me know, interesting to know that the original java library doesn't work but Android's does

Will be looking at it too

**Comment by ronpetit** [comment]
@xvrh Hello! I solved my problem

After too much investigation, I figure out that the Image dart package on the example is getting the image pixels in the ABGR format, changing it to RGBA make it work flawlessly for QRs taken with my phone camera and with a way less powerful camera (my real application). So at least for the dart side, this seems like the solution to me

I'm not an expert on images, but I discover this because the original example uses a PNG image, so I converted my JPGs to PNG and it started to work (No idea how is PNGs related to ABGR pixel format), but my first guess was that the pixel format was wrong, and as I said before, with RGBA it worked perfectly for JPGs

**Comment by xvrh** [comment]
@ronpetit good to know. Thanks!
